baseURL = 'https://riyt.dev/'
languageCode = 'en-us'
title = 'Raphael Tannous'
theme = "nojs"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 2

  [[menus.main]]
    name = 'LeetCode Solutions'
    pageRef = '/leetcode-solutions'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

  [markup.highlight]
    anchorLineNos = true
    lineNos = "inline"
    noClasses = false


[params]
  [params.footer]
    text = "Slop made by a human :)"
