baseURL = 'https://riyt.dev/'
languageCode = 'en-us'
title = 'Raphael Tannous'
theme = "nojs"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 2
